# action.yml
name: 'Get tag version from Pull Request labels'
description: 'Define the next release tag using PR label'
inputs:
  crash_on_error:
    description: 'If set to "true", the action will crash if an error occurs'
    required: false
    default: "true"
outputs:
  tag:
    description: 'The new release tag version'
runs:
  using: 'docker'
  image: 'Dockerfile'
